version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '5442:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - ziwatt

networks:
  ziwatt:
volumes:
  db_data:
